# Generated by Django 5.1.2 on 2025-02-04 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('requested', 'Demandée'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('paid', 'Payée'), ('ongoing', 'En cours'), ('completed', 'Terminée'), ('canceled', 'Annulée')], default='requested', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.car')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
