# Generated by Django 5.1.2 on 2025-02-04 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/images/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléversement')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.PositiveIntegerField(verbose_name='Année de fabrication')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('electric', 'Électrique'), ('hybrid', 'Hybride')], max_length=50, verbose_name='Type de carburant')),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], max_length=50, verbose_name='Transmission')),
                ('seats', models.PositiveIntegerField(verbose_name='Nombre de sièges')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix par jour (€)')),
                ('location', models.CharField(max_length=255, verbose_name='Localisation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_available', models.BooleanField(default=False, verbose_name='Disponible à la location')),
                ('status', models.CharField(choices=[('pending', 'En attente de vérification'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=50, verbose_name='Statut')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Raison du rejet')),
                ('main_image', models.ImageField(upload_to='cars/main_images/', verbose_name='Image principale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('additional_images', models.ManyToManyField(blank=True, related_name='car_images', to='listings.carimage', verbose_name='Images supplémentaires')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'ordering': ['-created_at'],
            },
        ),
    ]
