# Generated by Django 5.1.2 on 2025-02-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_carimage_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='car',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='car',
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix par jour (DZD)')),
                ('main_image', models.ImageField(upload_to='cars/main_images/', verbose_name='Image principale')),
                ('duree_minimale', models.PositiveIntegerField(default=1, help_text='Durée minimale de location en jours')),
                ('duree_maximale', models.PositiveIntegerField(default=7, help_text='Durée maximale de location en jours')),
                ('is_active', models.BooleanField(default=True, verbose_name='Annonce active ?')),
                ('additional_images', models.ManyToManyField(blank=True, related_name='annonces', to='listings.carimage', verbose_name='Images supplémentaires')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annonce', to='listings.car')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
            },
        ),
        migrations.AddField(
            model_name='carimage',
            name='annonce',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.annonce', verbose_name='Annonce associée'),
            preserve_default=False,
        ),
    ]
