# Generated by Django 5.1.2 on 2025-02-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_car_additional_images_remove_car_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
