# Generated by Django 5.1.2 on 2025-02-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_annonce_additional_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
