# Generated by Django 5.1.2 on 2025-02-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_car_latitude_car_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(choices=[(2, '2 sièges'), (4, '4 sièges'), (5, '5 sièges'), (7, '7 sièges'), (9, '9 sièges')], verbose_name='Nombre de sièges'),
        ),
    ]
